travis:
  secure:
    BINSTAR_TOKEN: f3e0e2kvgfHTBxHRTNyUdxBqdLVZWJxP1PI7scE+A5fwv/AnEW1tB4QK6CJJMOGRCjCi7SV6wd9T90z1TjCOPIMiTWphdJWoxQH6BpcHEvTydNIFaJD09aV56rJhBWbyLmwm3PVvwv7lCtZJNj2qVOPxhHIe5VfQrrLU78nPT0TJuuREqeebdPxrBdkB4DmLRCBSgmWw+BRwqugjLvcVjThNjQvdIoQPi3w3enwNX9ofunnbX6d2M8WmqrFeUMJ/wc8yNzMu0FMbBceeQ4730m30QF6yGj+KPyT+xrsLDHIGdFGwEPEhSen5D2n+4sC3e4FIwHOuZZKTNpkFaeg4J7ks5s70Dze6t61iA1/UwAni8qSCddn0ztdfvWIAnbpyRYDdUMd43BWsC76+XNRtfIH5GobOxbQDJruYBoa2PARx68JA1AbUzfERlBVw7PvsLeDlbUE6C55z5aTCAKyqAqRS2OajBDuJY0wrX0HRFlkjsuco2BT1I/O/+vaX0QcMtdTjyUInh9zK8qf+J1/Fz7GnYSr7zrC5fXrWot/aQhRoOvQZ6aOe8j03cP0FaSaJxGTKR1cLc5zlf3xp5b3HXJgg5keQR20LsSrYszAXB5okcrWJhKgTrAYsS8eB/HP+P9VSaHqpuZ9OfQDMf3CSOZgdGJOhEshyw1bK+qO3v2g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
