travis:
  secure:
    BINSTAR_TOKEN: OuLdpdHMPGlgy42PdCOGYQLpug/1RMu0Z/84Y6T0caKKT7vAl4ZVFeSPv+ZB7EzJZxEatnCs3Z57ShGNI+482fVnQoJ/D22fHO4nhT+lOrH7NE8uj8h+cJ8xQJlND7cC6ULBE61bGuYv4coOfIlvGZC03jRFJwZ0GiE15rzldwfpy11d4/7eA03Nwc2PgdStp7k2Z+Y0QKjcmxOxCIZezFN4Dj+T0oXAzvyuHbRxifpJkO+BIOuXJTDSNy4TCPAdfvM0Q2pLFv12NEpFmCIEdQxa9Qfze/HKk36nxbhIjBpv5itHbSGEohhkX7yVGmiRbEA8eoJbt+1uxZhQ30XToaRZVV2/AzAh61S7Z/dDi9pthRNlb+fIGRXKIC15Um0LPJjrJqweuwUvdxPlcTqmA2Xkcc4ZeooU71evItgeGSOt2NiFRzZXGynCSN01vDye3yLKIIjAnb0Mh3d4yYCa1hd1binAMxF6YgQvmndldNfFVgqOCzX1KptBGboxcv/RIieMSWWWCKethSp4qXB7GnvGGQnUIGUf/zGvPjmfcUhaeYBZT44k6Io6HP/e14D6ZosxrLz5KzDH4JfHTaUOhR33zypIPTNDjfC1gcbdgbh1SWwDosMZjMLK8Xi+gFY3tLXrYEGdqzaii6b/G9Atysh0AJx7gqjPHpY8VkEGmUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
